### ISSUE TITLE
Getter with unit gives Unsupported kind 177

### ISSUE THREAD

**Issue by nojaf** [glutinum-org/cli#106]
Issue created from [Glutinum Tool](https:glutinum.net/#/editors/fsharp-code?typeScriptCode=MYGwhgzhAEBiD29oG8CwAoaXoHoBUe0AKgBYCm0w8IIZwALgJbwB2A5DIwCZktMBmjMgCcAdNDw4M2aAHMy9aNwAUASgBc0CPWGMWsgNwYAvkA)

**Glutinum version -** 0.7.0

**TypeScript**

```ts
class Foo {
    /** The collection's identifier. */
    get id(): string;
}
```

**Error**

```
Error while reading declaration in:
/index.d.ts(1,12)

Unsupported kind 177

--- Text ---

    /** The collection's identifier. */
    get id(): string;
---

--- Parent text ---
class Foo {
    /** The collection's identifier. */
    get id(): string;
}
---

Error: Error while reading declaration in:
/index.d.ts(1,12)

Unsupported kind 177

--- Text ---

    /** The collection's identifier. */
    get id(): string;
---

--- Parent text ---
class Foo {
    /** The collection's identifier. */
    get id(): string;
}
---
    at O4t (https://glutinum.net/assets/index-DrAd18Ch.js:30529:12592)
    at Glutinum.Converter.Reader.Types.ITypeScriptReader.ReadDeclaration61B89E55 (https://glutinum.net/assets/index-DrAd18Ch.js:30893:130650)
    at https://glutinum.net/assets/index-DrAd18Ch.js:30529:713
    at https://glutinum.net/assets/index-DrAd18Ch.js:11:17883
    at OO (https://glutinum.net/assets/index-DrAd18Ch.js:11:16243)
    at j_ (https://glutinum.net/assets/index-DrAd18Ch.js:11:17855)
    at A4t (https://glutinum.net/assets/index-DrAd18Ch.js:30529:628)
    at Glutinum.Converter.Reader.Types.ITypeScriptReader.ReadClassDeclarationZ4558F325 (https://glutinum.net/assets/index-DrAd18Ch.js:30893:129435)
    at N4t (https://glutinum.net/assets/index-DrAd18Ch.js:30529:3391)
    at Glutinum.Converter.Reader.Types.ITypeScriptReader.ReadNode6C0FD055 (https://glutinum.net/assets/index-DrAd18Ch.js:30893:130034)
```

**Problem description**

A bit of a follow up on the firebase bindings, tried `bun cli.js node_modules/@firebase/firestore/dist/index.d.ts`.

**Comment by nojaf** [comment]
Nitpick:

> Issue created from [Glutinum Tool](https://github.com/glutinum-org/cli/issues/glutinum.net/#/editors/fsharp-code?typeScriptCode=MYGwhgzhAEBiD29oG8CwAoaXoHoBUe0AKgBYCm0w8IIZwALgJbwB2A5DIwCZktMBmjMgCcAdNDw4M2aAHMy9aNwAUASgBc0CPWGMWsgNwYAvkA)

this link doesn't seem to be working.

And when using the correct link it still doesn't work: https://glutinum.net/#/editors/fsharp-code?typeScriptCode=MYGwhgzhAEBiD29oG8CwAoaXoHoBUe0AKgBYCm0w8IIZwALgJbwB2A5DIwCZktMBmjMgCcAdNDw4M2aAHMy9aNwAUASgBc0CPWGMWsgNwYAvkA
Is the tool not updating on commits to main?

**Comment by MangelMaxime** [comment]
> Nitpick:
> 
> > Issue created from [Glutinum Tool](https://github.com/glutinum-org/cli/issues/glutinum.net/?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen#/editors/fsharp-code?typeScriptCode=MYGwhgzhAEBiD29oG8CwAoaXoHoBUe0AKgBYCm0w8IIZwALgJbwB2A5DIwCZktMBmjMgCcAdNDw4M2aAHMy9aNwAUASgBc0CPWGMWsgNwYAvkA)
> 
> this link doesn't seem to be working.

It seems like I broke it indeed.

> And when using the correct link it still doesn't work: [glutinum.net](https://glutinum.net/#/editors/fsharp-code?typeScriptCode=MYGwhgzhAEBiD29oG8CwAoaXoHoBUe0AKgBYCm0w8IIZwALgJbwB2A5DIwCZktMBmjMgCcAdNDw4M2aAHMy9aNwAUASgBc0CPWGMWsgNwYAvkA)
> Is the tool not updating on commits to main?

I update the web tool just now.

It is not updated (yet?) automatically when committing on main.

I could do it, the only issue is that the reported version on the tool is wrong because I need to make a "real" release to have it updated. I will look into it, I think I have an idea on how to generate version like `0.8.0-beta` based on the git history state.
