### ISSUE TITLE
Update the web tool, on every commit pushed to main

### ISSUE THREAD

**Issue by MangelMaxime** [glutinum-org/cli#109]
I didn't do it up to now, because the reported version is wrong as I need to make a "real" release to have it bumped.

However, using the git history it should be possible to detect that we are ahead of the current release version and thanks to that generate a web tool of version `0.8.0-preview` if the last released version is `0.7.0`.

**Comment by nojaf** [comment]
FWIIW: I think in Fantomas we just use the latest git commit SHA on main.

**Comment by MangelMaxime** [comment]
Ah right you have both `Main` and the preview tab.

**Comment by goswinr** [comment]
Thanks! It's great to always have an updated webtool! Especially for a constantly improving project!
