### ISSUE TITLE
Add support for `MappedType`

### ISSUE THREAD

**Issue by MangelMaxime** [glutinum-org/cli#119]
TypeScript documentation: 

```ts
declare const NODES: readonly ["a", "button"];
type Primitives = {
    [E in (typeof NODES)[number]]: boolean;
};
```

translates into

```fs
[<AllowNullLiteral>]
[<Interface>]
type Primitives =
    abstract member a: bool with get, set
    abstract member button: bool with get, set
```

Example of npm package using this features:

React or similar packages will use this kind of features.

**Comment by roboz0r** [comment]
An example of this kind of syntax is being used in [`@radix-ui/react-primitive` ](https://www.npmjs.com/package/@radix-ui/react-primitive)
