### ISSUE TITLE
handling of function utility types ThisParameterType/ReturnType

### ISSUE THREAD

**Issue by joprice** [glutinum-org/cli#127]
TypeScript documentation:  https://www.typescriptlang.org/docs/handbook/utility-types.html#thisparametertypetype

Issue created from [Glutinum Tool](https://glutinum.net/#/editors/fsharp-code?typeScriptCode=ATCmA8AcHsCcBdgEsB29SwGYEMDGpgBhaNCeAWWxWwHMNgBvAKBFeAHoAqTltkT4AHFQieAAsCuAK6xYoNMDzwkAN0kl04eLz6d2O1ktWgAFAEoAXEQ1kA3AZBceffsABKUlMHEFMX3NgANoEARngA1sAA7kjiwNAhAFaguIgAziKKad4SwNKy8ohGank2Wg6uAAKQ2LDYALalpFrAAIIoAJ7xSSmi0MAZRdk+eTJyCsXqzdouwALVtQ3Afm15QaER3v0hBEj19aAAJkjY6IFdsJ7RsWKoigOQKUiYSLhNmjMu8zV1jeJIaVasBo8UgyhIQWAcnwxlgW2AO2AUgyh2WcDWwVQIL8FTmwAWv0UwOy0DBSAhgSJNCkBzQ2UwcCitUOR3hONmegqMXEAB5WmAtPJDtlPOEUNAoigANoAXQANMAAGIC9AoYXAEwAOm1tRoaSsrTMwAAvAA+dwiGQoAAqHUePMVptNJlwZXgVmI0wVfisioV-0BwIA-FZrbc0gAFRYHdCwW32x0K7Wa3X6tqWC3wK3x0AO032FxOXECABCqFRVG6yVSWRykjGhXeZA16OwDyeLzeJFAZmL+J+SylrumMuAAHkyRTzu3cM8uiNhx9ordcGJgB1oFJolQ+lk0kgaCg+wSlvBdZl2l0EtXd1EV2u24vmyhQKz4NsCINi-oXCFyzzrWdJ8tA9N1-XPd1gGtDNrQLPgiw5YAAFFqBCQIpiXeoqFoUBaU+XQfz4eRsDQ0wMwDOC2AQr5gAAEQBEj0KbFosOoOg8O-CpjjSRiyKsCjeAAXyAA)

**Glutinum version -** 0.11.0-preview

**TypeScript**

```ts
  export interface ContextManager {
      /**
       * Get the current active context
       */
      active(): Context;
      /**
       * Run the fn callback with object set as the current active context
       * @param context Any object to set as the current active context
       * @param fn A callback to be immediately run within a specific context
       * @param thisArg optional receiver to be used for calling fn
       * @param args optional arguments forwarded to fn
       */
      with<A extends unknown[], F extends (...args: A) => ReturnType<F>>(context: Context, fn: F, thisArg?: ThisParameterType<F>, ...args: A): ReturnType<F>;
      /**
       * Bind an object as the current context (or a specific one)
       * @param [context] Optionally specify the context which you want to assign
       * @param target Any object to which a context need to be set
       */
      bind<T>(context: Context, target: T): T;
      /**
       * Enable context management
       */
      enable(): this;
      /**
       * Disable context management
       */
      disable(): this;
  }
```

**FSharp**

```fs
module rec Glutinum

open Fable.Core
open Fable.Core.JsInterop
open System

[<AllowNullLiteral>]
[<Interface>]
type ContextManager =
    /// <summary>
    /// Get the current active context
    /// </summary>
    abstract member active: unit -> Context
    /// <summary>
    /// Run the fn callback with object set as the current active context
    /// </summary>
    /// <param name="context">
    /// Any object to set as the current active context
    /// </param>
    /// <param name="fn">
    /// A callback to be immediately run within a specific context
    /// </param>
    /// <param name="thisArg">
    /// optional receiver to be used for calling fn
    /// </param>
    /// <param name="args">
    /// optional arguments forwarded to fn
    /// </param>
    abstract member ``with``: context: Context * fn: 'F * ?thisArg: ThisParameterType<'F> * [<ParamArray>] args: 'A [] -> ReturnType<'F>
    /// <summary>
    /// Bind an object as the current context (or a specific one)
    /// </summary>
    /// <param name="context">
    /// Optionally specify the context which you want to assign
    /// </param>
    /// <param name="target">
    /// Any object to which a context need to be set
    /// </param>
    abstract member bind: context: Context * target: 'T -> 'T
    /// <summary>
    /// Enable context management
    /// </summary>
    abstract member enable: unit -> ContextManager
    /// <summary>
    /// Disable context management
    /// </summary>
    abstract member disable: unit -> ContextManager

```

**Problem description**

The `ThisParameterType` and `ReturnType` utility type are left unprocessed. I'm not sure what type they should map to. Maybe just become generic types?

```fs
 abstract member ``with``<'a, 'b, 'this, 'A>:
      context: Context * fn: ('a -> 'b) * ?thisArg: 'this * [<ParamArray>] args: 'A[] -> 'b
```

Example of npm package using this features:

`@opentelemetry/api` uses this in `node_modules/@opentelemetry/api/build/src/context/types.d.ts`

docs: https://open-telemetry.github.io/opentelemetry-js/interfaces/_opentelemetry_api.ContextManager.html#with

**Comment by MangelMaxime** [comment]
From what I see only

- `ThisParameterType` should be map to either the concrete type behind its arguments or the generic.
- Same goes for `ReturnType`

I suppose the rule will be something like that:

1. If a generic is provided returns the generic
2. Otherwise, returns the concrete type or `obj`

**Comment by MangelMaxime** [comment]
Generation is not perfect but fixing this issue #145 would take too much time compared to the current generation, will be improved in the future at least the generated code should compile now.
