### ISSUE TITLE
Consider using `delegate` to represents `FunctionType`

### ISSUE THREAD

**Issue by MangelMaxime** [glutinum-org/cli#143]
History of the discussion available here #135 

By using delegate, we keep the parameter names information.

Need to check, if by using `delegate` we can still set the property on the interface. And what impact it has globally, perhaps we can also sometimes use delegates and sometimes flat functions.

**Comment by MangelMaxime** [comment]
I am taking a look at this issue and it seems like `FunctionType` is only used inside of `interface` or `class` methods in TypeScript.

So I am looking to make the F# output friendlier by using delegates.

My current idea, is if there is 0 or 1 parameters then I am generating a lambda.

Otherwise, it will generate a `delegate`.

The reason for that is I think for 1 parameter having the name of the parameter don't add a lot of value compared to the noise in the user output. Like with everything, it can be subject to change based on UX and feedbacks overtime.

I wanted to explains the reasoning to keep a track and in case someone as another vision.

cc @roboz0r (because we had a small chat about it on Discord)

**Comment by roboz0r** [comment]
Seems like the only major downside to `delegate` is the user must call the function using `.Invoke`. If generating the code we could also generate extensions that allow you to call the method naturally. `inline` means there's no extra js in the [output](https://fable.io/repl/#?code=C4TwDgpgBAwghgGwQIzgYwNZQLxQCYQIQDmcw0A9gGZTACWwRAXAM7ABOdAdsVAFRQAthBYs4xCKw7deFMPQpcoAWgB8UAK5cGAWABQ+0JCgARQiTLRs+qLahxkbdumBCIg5BHb2i7YE1hEFHQsAHcGAAsoCWAAGhYIYH1DcGgzIlJyKHDgKJs7YQ8vKG4EbmhcuhYAOgBBX2AACnpGSScZWLdRcTbpHig5BS4AShwofLs7SprEL2BqgEkuADcKDAhmhiJO4W6JYeS9Ilc0IPSLcka4APPMiFHcODqGzdaxgCI4d52RMQkxgByinuQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltZWYiFOOzq4eJKS6AFxKSjRcpADWAObxUhBKAAIA7kjhx6TcfGBRl9d9t1z3ugWnAEzxAAzxAGYlBIaLowH1KFAkPgeLpKLoAKzkdAoRxIbT5QrFUo1CpzXF1JbuFbrTbbPaHY5nJ43O6w4Gg8EQSHQ96nACM8R+vwZYIhSChMIeWRymImOPKYHg1UliwaJI2Wx2ByOfWpV1pb3pui0aCEvQgHPinKBOvQ+r6IrGWMmBPgCBKIFQGAd4RSQkkUBQul0HlRFCkPBQOXRRTgOFwECE5HCRnBXEwXvCAo8HA44qjMbj3GlSjdevtjsgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA). 

```fs
type Callback = delegate of title:string * message:string option -> unit

type Delegate =
    abstract member alert: Callback with get,set

type Delegate with 
    member inline this.Alert(title:string, message:string option) = 
        this.alert.Invoke(title, message)

let callDelegate(a: Delegate) = a.Alert(title = "a", message = None)
```

```js
export function callDelegate(a) {
    a.alert("a", undefined);
}
```

**Comment by MangelMaxime** [comment]
That's an interesting idea, I opened a new issue to keep track of this idea and to list the impact/drawback it can have.

See #144

**Comment by roboz0r** [comment]
Not sure if this belongs here or in #144 (or a new issue) but I tried hacking on the `ParamObject` syntax and came up with the following that avoids extension members but keeps the need to change case or other minor name change:

```fs
open Fable.Core

type Callback = delegate of title:string * message:string option -> unit

[<AllowNullLiteral>]
[<Global>]
type Delegate
    [<ParamObject; Emit("$0")>]
    (alert: Callback) =
    member val alert: Callback = jsNative with get, set
    
    [<CompiledName("alert")>]
    member inline this.Alert(title, message) = this.alert.Invoke(title, message)
    

let d = Delegate(fun title message -> printfn "%s %A" title message)
let callDelegate(a: Delegate) = a.Alert("a", None)

callDelegate d
d.Alert("a", None)
d.alert <- (fun title message -> printfn "changed %s %A" title message)
d.Alert("a", None)
```

**Comment by MangelMaxime** [comment]
What does `CompiledName` do ? It was not required before for the same code.

I don't think this new code can be used, because it is using a class and F# classes don't support multi inheritance.

**Comment by roboz0r** [comment]
Without `CompiledName` the method call still comes out as `d.Alert` in the js instead of `d.alert`

**Comment by roboz0r** [comment]
You can include an interface without changing the output JS:

```fs
[<AllowNullLiteral>]
type IDelegate =
    abstract member alert: Callback with get, set

[<AllowNullLiteral>]
[<Global>]
type Delegate
    [<ParamObject; Emit("$0")>]
    (alert: Callback) =
    member val alert: Callback = jsNative with get, set
    
    [<CompiledName("alert")>]
    member inline this.Alert(title, message) = this.alert.Invoke(title, message)

    interface IDelegate with
        member val alert: Callback = jsNative with get, set
```

**Comment by MangelMaxime** [comment]
A first implementation with delegate has been done, the rest is tracked in the new issue.
