### ISSUE TITLE
Symbol property name causes invalid F# code generation

### ISSUE THREAD

**Issue by NatElkins** [glutinum-org/cli#154]
Issue created from [Glutinum Tool](https://glutinum.net/#/editors/fsharp-code?typeScriptCode=JAUwHgDg9gTgLgAgMYBsCGBnDCAia5oAqMaAdhgGYgwICWAthCiPSKXNgJJzVoBGzADwBtegxCEAnhBAAuBBjgxapAOYAaOj3ry8BYmUrVuLALoA+BAG8AUMGAB6AFRO7wBE4QAlEEtogANxBsOAALEAQAE3w0BCVDKhpabQQKWARY1Vog0gQxVjjpEAA6Nw8yzwABCDQSejzxKRkEQnCGgrgiuKgEVV84tuiCOJJyRK0WVNhNDABXJFCM7AADHjA4ByY0FWWEdOWGND7NtWXS+w8EAFlxEK6UKCgAawRZiGxaiKRMEABaFQwbAwyWyJQqFQQAGUZEhaGgUO0Ip0ZBhZBDfghVuANrNlL8ULRFLtACgEAAKAIIKPxqBAAd2Si1WUEh1NUAAoAJTLECRBAAVWU2EBNRIPF5fEkmIAOjApaQzi0ehgYbQKJLYkhcRh0tBgXBaFBcioBhEKLRmOoIYDEGEIgLaABybAUEiqVjsbqYgAyAGZ1ABWZaaWnhGARH10EJtAmkCKkWb0PjUDKkXn+yMm5BQFAJ3LxxPUc7uJwONx9OBs-ISIryRTKNQc3QxAxjYwpAA+r1TIDNsciAG4bG5nK4Lp5Ib4PojCs04D0hrF4q2kil6GgIBAVKoi+UxwhqrU0PUq00Iq0IlWZ0ilf1bVEYlMYMVrrcr0K52HecaHrTk99AcGDLID8-zkECIJBAgDzPNgbw7lUIpHggATwrMZ6DA+S5GCukxpDQd5ZDk07ImCY6lvY1qVo0NZUvWGjIahci4M2ozYSY9CNshUC0AOQ72COELkigP7YMkvD6oaAwwFAsyqIsd4LiMCTJmJ9AYPBEIHnUwHCXwaBIE8FC5AAwvCKB6QZj4TKKBq5GE0myfJGHDFh4yqepmmIfUYSEuSMCqC0bSrKEhK7EghprIgsyAryIZsHQpABM8W6ZqEZCRMwNAULMpBIBJpDweRwB4QAovpoRst8un6YZpDyGyqlNvorGJOxmgnjRdZbpoC4tthTVEC11AcggAC8lhJTxmg+RgfmqAA-PIZCSJxk28cOLgQgA4v0sSxrS1n4Ok9JhJmyyiOImiqaYuw1LQMDOukIDlQgIDMO6iDGjN94uUNT4VEVwiQpIibZsUYmirApicvIJgkAIIBw0dMAiB1Mi1qyV3aANfWtdoFiDsAAC+QA)

**Glutinum version -** 0.11.0-preview

**TypeScript**

```ts
	export class DataTransfer implements Iterable<[mimeType: string, item: DataTransferItem]> {
		/**
		 * Retrieves the data transfer item for a given mime type.
		 *
		 * @param mimeType The mime type to get the data transfer item for, such as `text/plain` or `image/png`.
		 * Mimes type look ups are case-insensitive.
		 *
		 * Special mime types:
		 * - `text/uri-list` — A string with `toString()`ed Uris separated by `\r\n`. To specify a cursor position in the file,
		 * set the Uri's fragment to `L3,5`, where 3 is the line number and 5 is the column number.
		 */
		get(mimeType: string): DataTransferItem | undefined;

		/**
		 * Sets a mime type to data transfer item mapping.
		 *
		 * @param mimeType The mime type to set the data for. Mimes types stored in lower case, with case-insensitive looks up.
		 * @param value The data transfer item for the given mime type.
		 */
		set(mimeType: string, value: DataTransferItem): void;

		/**
		 * Allows iteration through the data transfer items.
		 *
		 * @param callbackfn Callback for iteration through the data transfer items.
		 * @param thisArg The `this` context used when invoking the handler function.
		 */
		forEach(callbackfn: (item: DataTransferItem, mimeType: string, dataTransfer: DataTransfer) => void, thisArg?: any): void;

		/**
		 * Get a new iterator with the `[mime, item]` pairs for each element in this data transfer.
		 */
		[Symbol.iterator](): IterableIterator<[mimeType: string, item: DataTransferItem]>;
	}
```

**FSharp**

```fs
module rec Glutinum

open Fable.Core
open Fable.Core.JsInterop
open System

[<AbstractClass>]
[<Erase>]
type Exports =
    [<Import("DataTransfer", "REPLACE_ME_WITH_MODULE_NAME"); EmitConstructor>]
    static member DataTransfer () : DataTransfer = nativeOnly

[<AllowNullLiteral>]
[<Interface>]
type DataTransfer =
    inherit Iterable<string * DataTransferItem>
    abstract member get: mimeType: string -> DataTransferItem option
    abstract member set: mimeType: string * value: DataTransferItem -> unit
    abstract member forEach: callbackfn: DataTransfer.forEach.callbackfn * ?thisArg: obj -> unit
    abstract member [Symbol_iterator]: unit -> IterableIterator<string * DataTransferItem>

module DataTransfer =

    module forEach =

        type callbackfn =
            delegate of item: DataTransferItem * mimeType: string * dataTransfer: DataTransfer -> unit

```

**Problem description**

I'm trying to create bindings to `@types/vscode`.  The `abstract member [Symbol_iterator]: unit -> IterableIterator<string * DataTransferItem>` is not valid F# code.

Also `Iterable` isn't implemented, but I think that's more likely to be a Fable thing.

**Comment by MangelMaxime** [comment]
This is fixed in the preview version (available online)
