### ISSUE TITLE
invalid code generated for empty array type literal 

### ISSUE THREAD

**Issue by joprice** [glutinum-org/cli#158]
Issue created from [Glutinum Tool](https://glutinum.net/#/editors/fsharp-code?typeScriptCode=C4TwDgpgBAGlDeAoKUBmBLAdgEwDwEEoIAPYCHAZyn0xH2AHsBbAFQibABsBDMqAXijdaAPgAUFCNwBOAYwAWAZWDSAXFAoqsAcwA0UMDO5MKAfnUBtALoBKdfWYBJTJuGyILcBAIioAHygAVxwIDEwIbABuRABfIA)

**Glutinum version -** 0.11.0-preview

**TypeScript**

```ts
type X {
  find<A extends AnyAtomTemplate = any>(searchStr: string, params?: []): AtomInstanceType<A> | undefined;
}
```

**FSharp**

```fs
module rec Glutinum

open Fable.Core
open Fable.Core.JsInterop
open System

[<AllowNullLiteral>]
[<Interface>]
type X =
    abstract member find: searchStr: string * ?``params``:  -> obj option

```

**Problem description**

I'm not sure what the meaning of the empty array type is, but it happens to cause a parse error in the generated code, as no type (not even a placeholder `obj` is generated). This pattern appears a few times in the zedux https://github.com/Omnistac/zedux api.

**Comment by MangelMaxime** [comment]
I suppose in this situation we want to generate `ResizeArray<obj>` it should be the most generic type for an array.

We could also go with `obj` but the user would not be informed that he needs to provide an array type.

**Comment by joprice** [comment]
I’ve used this api a bit more and this might actually be intended to only be used for type inference. That is, when the params are not provided or empty, the resulting type uses the default value for the type parameter instead of specializing it. So I ended up with two overloads, one with “params” and one without, so that the result type can vary based on the presence of the params parameter. In the general case I’m unsure what to do since for complex apis like this, a custom binding would probably be written anyway, but at least producing something that is valid syntax is an improvement.

**Comment by MangelMaxime** [comment]
> In the general case I’m unsure what to do since for complex apis like this, a custom binding would probably be written anyway, but at least producing something that is valid syntax is an improvement.

Definitely, we want Glutinum to generate a valid F# code. Then, it tries to optimise it has much as possible but sometimes a manual improvement will still be needed I think.

**Comment by MangelMaxime** [comment]
Actually, `[]` is not an empty array but a `TupleType` which is empty.

![CleanShot 2024-12-16 at 11 39 43@2x](https://github.com/user-attachments/assets/a7ed6eb9-c213-4abc-8ef6-5c65b435f7dc)

So for now I going to use `obj`
