### ISSUE TITLE
Consider adding `open Fable.Core.JS` to generated bindings

### ISSUE THREAD

**Issue by NatElkins** [glutinum-org/cli#168]
Issue created from [Glutinum Tool](https://glutinum.net/#/editors/fsharp-code?typeScriptCode=MYGwhgzhAEAqCmEAu0DeAoaXoBMxLAC5oBVASwDskBmAJgEEAnRsAT3QF8g)

**Glutinum version -** 0.12.0-preview

**TypeScript**

```ts
class Test {
    data: Uint32Array
}
```

**FSharp**

```fs
module rec Glutinum

open Fable.Core
open Fable.Core.JsInterop
open System

[<AbstractClass>]
[<Erase>]
type Exports =
    [<Import("Test", "REPLACE_ME_WITH_MODULE_NAME"); EmitConstructor>]
    static member Test () : Test = nativeOnly

[<AllowNullLiteral>]
[<Interface>]
type Test =
    abstract member data: Uint32Array with get, set

```

`Uint32Array` is implemented in `Fable.Core.JS` (as are many other commonly used types).  I had to do a bit of hunting to find it, might be better for DX to just add it to all bindings by default and the user will get an unused warning if it isn't used.  It would be best if it were detected automatically I suppose but that might be more effort than it's worth.  What do you think?

https://github.com/fable-compiler/Fable/blob/main/src/Fable.Core/Fable.Core.JS.fs

**Comment by MangelMaxime** [comment]
I am not opening `Fable.Core.JS` on purpose as it can easily pollute the name.

Currently, we deal with such types by adding a case to this function:

https://github.com/glutinum-org/cli/blob/b7e90308e4986429df8389fcb215a03d09c2f7da/src/Glutinum.Converter/Transform.fs#L144-L166

There is also the `ExposeTypeAlias` method that is used when we need to generate something like `type RegExp = Text.RegularExpressions.Regex`.

> It would be best if it were detected automatically I suppose but that might be more effort than it's worth.

Adding a `open Fable.Core.JS` only if needed, would require the equivalent of the current system so to not pollute the namespace keeping the current system works fine.

This position could be revisited in the future once `Glutinum.Types` grows bigger. For example, it is used if the generated need `ReadonlyArray`.

**Comment by NatElkins** [comment]
Got it, makes sense, I'll close then.

**Comment by MangelMaxime** [comment]
I opened https://github.com/glutinum-org/cli/issues/170 to keep track of your original issue.
