### ISSUE TITLE
`--out-file` doesn't respect file casing

### ISSUE THREAD

**Issue by baronfel** [glutinum-org/cli#23]
I was trying this on the Ionide helpers and discovered that the `--out-file` parameter tolower's the output file name:

```console
$ npx @glutinum/cli node_modules/vscode-languageclient/node.d.ts --out-file src/Fable.Import.VSCode.LanguageClient.fs

Generating binding file for node_modules/vscode-languageclient/node.d.ts
readNode: Unsupported kind 278
Bindings written to: D:\Code\ionide-vscode-helpers\src\fable.import.vscode.languageclient.fs
Success!
```

**Comment by MangelMaxime** [comment]
Ah yes, I know why it does that.

It is funny has this whole journey started because of VSCode bindings for me creating an extension. And I am really surprised that i doesn't crash on these bindings.

Version 0.3.1 has been released to fix this problem

**Comment by baronfel** [comment]
Oh Glutinum _does_ crash on those bindings, but I was starting with small issues :)

**Comment by MangelMaxime** [comment]
But it says success in the console 😇

**Comment by baronfel** [comment]
Oh, that one. The bindings were generated but they were empty because the source typing's file just imports from other files.

**Comment by MangelMaxime** [comment]
Oh I see, that explains why it "worked" then. 🤣
