### ISSUE TITLE
Request for webgpu

### ISSUE THREAD

**Issue by spatialfree** [glutinum-org/cli#25]
## Description of the package
[WebGPU](https://gpuweb.github.io/gpuweb/) is a modern API for accessing the capabilities of your GPU.

## Resources

- Github repo: [https://github.com/gpuweb/gpuweb](https://github.com/gpuweb/gpuweb)
- API Documentation: [https://gpuweb.github.io/gpuweb/](https://gpuweb.github.io/gpuweb/)
- API definitions: [https://gpuweb.github.io/types/](https://gpuweb.github.io/types/)

**Comment by MangelMaxime** [comment]
@spatialfree Can you please provide a link to the TypeScript definition files or the NPM package which contains them?

**Comment by spatialfree** [comment]
@MangelMaxime oh thx! yeah, no problem:
[https://github.com/gpuweb/types/blob/main/dist/index.d.ts](https://github.com/gpuweb/types/blob/main/dist/index.d.ts)
[https://www.npmjs.com/package/@webgpu/types](https://www.npmjs.com/package/@webgpu/types)

**Comment by spatialfree** [comment]
*solved here: https://github.com/glutinum-org/Glutinum.WebGPU

thanks again! :tada:
